### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ShaileshParmar11** [Sachin-chaurasiya/Code-Snippets-Builder#40]
- [x] Sign in/ sign up with google is redirecting back to sign in page, and account is getting created but not able to login
- [x] Need to add text "Profile" or "Account"
<img width="263" alt="image" src="https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/c1f57d59-4120-478a-9323-042f5719b9a8">

- [x] profile icon is blank
<img width="180" alt="image" src="https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/79d85b0f-10aa-4d66-9c33-e48aaecefd74">

- [x] "Not Verified" might sound better
<img width="143" alt="image" src="https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/5baa1947-b224-428c-967f-f057b7802768">

- [x] Top section is not aligned with other section
<img width="1266" alt="image" src="https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/9a2e3540-4b04-40e0-9408-47ea55d1e104">
placeholder is missing, title is center-aligned, description below title is missing

**Comment by Sachin-chaurasiya** [comment]
@ShaileshParmar11 , regarding this, verified and unverified terms are standard, so will keep that only.
>  "Not Verified" might sound better

**Comment by Sachin-chaurasiya** [comment]
@ShaileshParmar11 , Not able to reproduce this, recording might be helpful.
> Sign in/ sign up with google is redirecting back to sign in page, and account is getting created but not able to login

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 , Not able to reproduce this, recording might be helpful.
> 
> > Sign in/ sign up with google is redirecting back to sign in page, and account is getting created but not able to login

https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/8f6691f9-f38d-42d2-932d-f3dabb124693

**Comment by Sachin-chaurasiya** [comment]
> > @ShaileshParmar11 , Not able to reproduce this, recording might be helpful.
> > > Sign in/ sign up with google is redirecting back to sign in page, and account is getting created but not able to login
> 
>  Screen.Recording.2023-06-14.at.10.46.31.PM.mov

@ShaileshParmar11 , usually it's not reproducible, however, I can reproduce on incognito, I have added a toast message to have proper context why it's failing.

**Comment by Sachin-chaurasiya** [comment]
Thanks @ShaileshParmar11  for the feedbacks, I have try to address all of them.

**Comment by Sachin-chaurasiya** [comment]
> Thanks, @ShaileshParmar11 for the feedback, I have tried to address all of them.

@ShaileshParmar11 , Appwrite uses session cookies to store the session and your browser might be blocking the 3rd party cookies, that's why you are not able to log in.
