### ISSUE TITLE
change social media user name on the fly.

### ISSUE THREAD

**Issue by ShaileshParmar11** [Sachin-chaurasiya/Code-Snippets-Builder#60]
Allow user to change the social media use name on the fly

scenario:
lets say user want to place someone else username instead of there own. the field should be editable.

![image](https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/f4f72d81-53e2-4cca-bc82-e9872a50f960)

**Comment by Sachin-chaurasiya** [comment]
@ShaileshParmar11 , did you get a chance to look into this?

**Comment by Sachin-chaurasiya** [comment]
We will not allow users to change their social username on the fly because this will lead to data mismatch as they will have different usernames saved in their profile.
