### ISSUE TITLE
Is there a way to delete an editor, text box, or screenshot?

### ISSUE THREAD

**Issue by impressivewebs** [Sachin-chaurasiya/Code-Snippets-Builder#72]
I don't see a way to select and delete an element on the canvas after it's been added. Would be a nice feature.

**Comment by Sachin-chaurasiya** [comment]
Hello @impressivewebs , thanks for reaching out, selecting and deleting the element feature is already there. you can choose the node and press the delete button.

**Comment by impressivewebs** [comment]
Hi @Sachin-chaurasiya, ok it seems like you're half right. On my windows machine, I can delete a node by hitting the "backspace" key. But the actual "delete" key doesn't seem to do anything. Maybe it would be good to have both do the deletion. Anyhow, nice job on the tool, I will feature it in my newsletter (webtoolsweekly.com).

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya, ok it seems like you're half right. On my windows machine, I can delete a node by hitting the "backspace" key. But the actual "delete" key doesn't seem to do anything. Maybe it would be good to have both do the deletion. Anyhow, nice job on the tool, I will feature it in my newsletter ([webtoolsweekly.com](https://webtoolsweekly.com/)).

Thanks, @impressivewebs , I will check and try to have support for both keys.

**Comment by Sachin-chaurasiya** [comment]
Hello @impressivewebs , we have added support for both the keys with this PR #75 , can you please try and let us know, thanks

**Comment by impressivewebs** [comment]
@Sachin-chaurasiya Looks like it works, thanks!

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Looks like it works, thanks!

Shoutout to @anuj-kumary for quick hacking 👌🏻
