### ISSUE TITLE
add border-radius to editor's container

### ISSUE THREAD

**Issue by ShaileshParmar11** [Sachin-chaurasiya/Code-Snippets-Builder#97]
When selecting an editor, it becomes clear that its container does not have border radius.

<img width="1680" alt="image" src="https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/71748675/7b832fff-ea80-467d-9e6b-b579f9d1ddcc">

**Comment by SandipGyawali** [comment]
@ShaileshParmar11 can you assign me the issue?

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 can you assign me the issue?

@SandipGyawali, I have assigned the issue to you. Please let us know if you need any help. Thank you!

**Comment by SandipGyawali** [comment]
@ShaileshParmar11 i am having issue with the setup 

![image](https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/66510112/2b6536bd-4f27-40fa-93cb-c0c0a9604a71)

**Comment by ShaileshParmar11** [comment]
Can you please try removing PORT=3001 from script and start

**Comment by Sachin-chaurasiya** [comment]
Hey @SandipGyawali, just wanted to check if you had a chance to make any progress on this?

**Comment by Sachin-chaurasiya** [comment]
This issue has been fixed.

<img width="355" alt="image" src="https://github.com/Sachin-chaurasiya/Code-Snippets-Builder/assets/59080942/0e6254cb-1ea8-457e-8c41-8c2dfce6edfd">
